// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef ui_h
#define ui_h
#include <FL/Fl.H>
#include <FL/Fl_Chart.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Scroll.H>
extern Fl_Scroll *scroll;
#include <FL/Fl_Pack.H>
extern Fl_Pack *list;
#include <FL/Fl_Box.H>
extern Fl_Box *status;
#endif
